name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Permission
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test
        
      - name: UI Test
        run: ./gradlew connectedAndroidTest
       
      - name: Lint
        run: ./gradlew lint
       
      - name: Build
        run: ./gradlew build
